
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.dekuffet.omegacraft.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.dekuffet.omegacraft.item.YellowChaosEmeraldItem;
import net.dekuffet.omegacraft.item.WitheredNetherStarItem;
import net.dekuffet.omegacraft.item.WitherStormCoreItem;
import net.dekuffet.omegacraft.item.WhiteChaosEmeraldItem;
import net.dekuffet.omegacraft.item.WardenHeartItem;
import net.dekuffet.omegacraft.item.WardenCoreItem;
import net.dekuffet.omegacraft.item.TwoStarDragonBallItem;
import net.dekuffet.omegacraft.item.TurquoiseChaosEmeraldItem;
import net.dekuffet.omegacraft.item.ThreeStarDragonBallItem;
import net.dekuffet.omegacraft.item.SixStarDragonBallItem;
import net.dekuffet.omegacraft.item.SevenStarDragonBallItem;
import net.dekuffet.omegacraft.item.SenzuBeanItem;
import net.dekuffet.omegacraft.item.RubySwordItem;
import net.dekuffet.omegacraft.item.RubyShovelItem;
import net.dekuffet.omegacraft.item.RubyPickaxeItem;
import net.dekuffet.omegacraft.item.RubyItem;
import net.dekuffet.omegacraft.item.RubyHoeItem;
import net.dekuffet.omegacraft.item.RubyAxeItem;
import net.dekuffet.omegacraft.item.RubyArmorItem;
import net.dekuffet.omegacraft.item.RingItem;
import net.dekuffet.omegacraft.item.RedStoneDustItem;
import net.dekuffet.omegacraft.item.RedStarDragonBallSetItem;
import net.dekuffet.omegacraft.item.RedChaosEmeraldItem;
import net.dekuffet.omegacraft.item.RGBStickItem;
import net.dekuffet.omegacraft.item.RGBStarItem;
import net.dekuffet.omegacraft.item.RGBGemItem;
import net.dekuffet.omegacraft.item.PurpleChaosEmeraldItem;
import net.dekuffet.omegacraft.item.PureAgeEmeraldItem;
import net.dekuffet.omegacraft.item.PinkChaosEmeraldItem;
import net.dekuffet.omegacraft.item.OrangeChaosEmeraldItem;
import net.dekuffet.omegacraft.item.OofSwordItem;
import net.dekuffet.omegacraft.item.OofShovelItem;
import net.dekuffet.omegacraft.item.OofPickaxeItem;
import net.dekuffet.omegacraft.item.OofHoeItem;
import net.dekuffet.omegacraft.item.OofAxeItem;
import net.dekuffet.omegacraft.item.OofArmorItem;
import net.dekuffet.omegacraft.item.OneStarDragonBallItem;
import net.dekuffet.omegacraft.item.OPMItem;
import net.dekuffet.omegacraft.item.NetheriteDustItem;
import net.dekuffet.omegacraft.item.NetherCoreItem;
import net.dekuffet.omegacraft.item.MixedorehoeItem;
import net.dekuffet.omegacraft.item.MixedOreaItem;
import net.dekuffet.omegacraft.item.MixedOreSwordItem;
import net.dekuffet.omegacraft.item.MixedOreShovelItem;
import net.dekuffet.omegacraft.item.MixedOrePickAxeItem;
import net.dekuffet.omegacraft.item.MixedOreMeatIngotItem;
import net.dekuffet.omegacraft.item.MixedOreIngotItem;
import net.dekuffet.omegacraft.item.MixedOreBowItem;
import net.dekuffet.omegacraft.item.MixedOreAxeItem;
import net.dekuffet.omegacraft.item.MeltedNetheriteItem;
import net.dekuffet.omegacraft.item.MeatdustItem;
import net.dekuffet.omegacraft.item.MasterEmeraldItemItem;
import net.dekuffet.omegacraft.item.LapisDustItem;
import net.dekuffet.omegacraft.item.IronDustItem;
import net.dekuffet.omegacraft.item.IncompleteAdminStaffItem;
import net.dekuffet.omegacraft.item.GreenChaosEmeraldItem;
import net.dekuffet.omegacraft.item.GoldDustItem;
import net.dekuffet.omegacraft.item.FourStarDragonBallItem;
import net.dekuffet.omegacraft.item.FiveStarDragonBallItem;
import net.dekuffet.omegacraft.item.EnderiteScrapItem;
import net.dekuffet.omegacraft.item.EnderiteIngotItem;
import net.dekuffet.omegacraft.item.EnderCoreItem;
import net.dekuffet.omegacraft.item.EndPortalSlotItem;
import net.dekuffet.omegacraft.item.EndPortalSideFramesItem;
import net.dekuffet.omegacraft.item.EndEssenceItem;
import net.dekuffet.omegacraft.item.EmptyCoreItem;
import net.dekuffet.omegacraft.item.EmeraldDustItem;
import net.dekuffet.omegacraft.item.DrainedChaosEmeraldItem;
import net.dekuffet.omegacraft.item.DiamondStickItem;
import net.dekuffet.omegacraft.item.DiamondDustItem;
import net.dekuffet.omegacraft.item.CreativeEssenceItem;
import net.dekuffet.omegacraft.item.CopperDustItem;
import net.dekuffet.omegacraft.item.CommandCoreItem;
import net.dekuffet.omegacraft.item.CommandBookItem;
import net.dekuffet.omegacraft.item.CoalDustItem;
import net.dekuffet.omegacraft.item.BlueChaosEmeraldItem;
import net.dekuffet.omegacraft.item.AquamarineSwordItem;
import net.dekuffet.omegacraft.item.AquamarineShovelItem;
import net.dekuffet.omegacraft.item.AquamarinePickaxeItem;
import net.dekuffet.omegacraft.item.AquamarineItem;
import net.dekuffet.omegacraft.item.AquamarineHoeItem;
import net.dekuffet.omegacraft.item.AquamarineAxeItem;
import net.dekuffet.omegacraft.item.AquamarineArmorItem;
import net.dekuffet.omegacraft.item.AdminStaffItem;
import net.dekuffet.omegacraft.item.AdminRingItem;
import net.dekuffet.omegacraft.item.AdminArmorItem;
import net.dekuffet.omegacraft.OmegacraftMod;

public class OmegacraftModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, OmegacraftMod.MODID);
	public static final RegistryObject<Item> PURE_AGE_EMERALD_BLOCK = block(OmegacraftModBlocks.PURE_AGE_EMERALD_BLOCK);
	public static final RegistryObject<Item> MIXED_ORE_BLOCK = block(OmegacraftModBlocks.MIXED_ORE_BLOCK);
	public static final RegistryObject<Item> AQUAMARINE_BLOCK = block(OmegacraftModBlocks.AQUAMARINE_BLOCK);
	public static final RegistryObject<Item> RUBY_BLOCK = block(OmegacraftModBlocks.RUBY_BLOCK);
	public static final RegistryObject<Item> ENDERITE_BLOCK = block(OmegacraftModBlocks.ENDERITE_BLOCK);
	public static final RegistryObject<Item> PURE_EMERALD_ORE = block(OmegacraftModBlocks.PURE_EMERALD_ORE);
	public static final RegistryObject<Item> MIXED_ORE = block(OmegacraftModBlocks.MIXED_ORE);
	public static final RegistryObject<Item> AQUAMARINE_ORE = block(OmegacraftModBlocks.AQUAMARINE_ORE);
	public static final RegistryObject<Item> DEEPSLATE_MIXED_ORE = block(OmegacraftModBlocks.DEEPSLATE_MIXED_ORE);
	public static final RegistryObject<Item> DEEPSLATE_AQUAMARINE_ORE = block(OmegacraftModBlocks.DEEPSLATE_AQUAMARINE_ORE);
	public static final RegistryObject<Item> RUBY_ORE = block(OmegacraftModBlocks.RUBY_ORE);
	public static final RegistryObject<Item> ENDERITE_ORE = block(OmegacraftModBlocks.ENDERITE_ORE);
	public static final RegistryObject<Item> MASSIVE_CHEST_BLOCK = block(OmegacraftModBlocks.MASSIVE_CHEST_BLOCK);
	public static final RegistryObject<Item> ORE_CRUSHER = block(OmegacraftModBlocks.ORE_CRUSHER);
	public static final RegistryObject<Item> KAMIS_WORKSHOP = block(OmegacraftModBlocks.KAMIS_WORKSHOP);
	public static final RegistryObject<Item> GREEN_CHAOS_EMERALD = REGISTRY.register("green_chaos_emerald", () -> new GreenChaosEmeraldItem());
	public static final RegistryObject<Item> RED_CHAOS_EMERALD = REGISTRY.register("red_chaos_emerald", () -> new RedChaosEmeraldItem());
	public static final RegistryObject<Item> BLUE_CHAOS_EMERALD = REGISTRY.register("blue_chaos_emerald", () -> new BlueChaosEmeraldItem());
	public static final RegistryObject<Item> WHITE_CHAOS_EMERALD = REGISTRY.register("white_chaos_emerald", () -> new WhiteChaosEmeraldItem());
	public static final RegistryObject<Item> YELLOW_CHAOS_EMERALD = REGISTRY.register("yellow_chaos_emerald", () -> new YellowChaosEmeraldItem());
	public static final RegistryObject<Item> PURPLE_CHAOS_EMERALD = REGISTRY.register("purple_chaos_emerald", () -> new PurpleChaosEmeraldItem());
	public static final RegistryObject<Item> PINK_CHAOS_EMERALD = REGISTRY.register("pink_chaos_emerald", () -> new PinkChaosEmeraldItem());
	public static final RegistryObject<Item> ORANGE_CHAOS_EMERALD = REGISTRY.register("orange_chaos_emerald", () -> new OrangeChaosEmeraldItem());
	public static final RegistryObject<Item> TURQUOISE_CHAOS_EMERALD = REGISTRY.register("turquoise_chaos_emerald", () -> new TurquoiseChaosEmeraldItem());
	public static final RegistryObject<Item> DRAINED_CHAOS_EMERALD = REGISTRY.register("drained_chaos_emerald", () -> new DrainedChaosEmeraldItem());
	public static final RegistryObject<Item> ONE_STAR_DRAGON_BALL = REGISTRY.register("one_star_dragon_ball", () -> new OneStarDragonBallItem());
	public static final RegistryObject<Item> TWO_STAR_DRAGON_BALL = REGISTRY.register("two_star_dragon_ball", () -> new TwoStarDragonBallItem());
	public static final RegistryObject<Item> THREE_STAR_DRAGON_BALL = REGISTRY.register("three_star_dragon_ball", () -> new ThreeStarDragonBallItem());
	public static final RegistryObject<Item> FOUR_STAR_DRAGON_BALL = REGISTRY.register("four_star_dragon_ball", () -> new FourStarDragonBallItem());
	public static final RegistryObject<Item> FIVE_STAR_DRAGON_BALL = REGISTRY.register("five_star_dragon_ball", () -> new FiveStarDragonBallItem());
	public static final RegistryObject<Item> SIX_STAR_DRAGON_BALL = REGISTRY.register("six_star_dragon_ball", () -> new SixStarDragonBallItem());
	public static final RegistryObject<Item> SEVEN_STAR_DRAGON_BALL = REGISTRY.register("seven_star_dragon_ball", () -> new SevenStarDragonBallItem());
	public static final RegistryObject<Item> RED_STAR_DRAGON_BALL_SET = REGISTRY.register("red_star_dragon_ball_set", () -> new RedStarDragonBallSetItem());
	public static final RegistryObject<Item> PURE_AGE_EMERALD = REGISTRY.register("pure_age_emerald", () -> new PureAgeEmeraldItem());
	public static final RegistryObject<Item> MIXED_ORE_INGOT = REGISTRY.register("mixed_ore_ingot", () -> new MixedOreIngotItem());
	public static final RegistryObject<Item> AQUAMARINE = REGISTRY.register("aquamarine", () -> new AquamarineItem());
	public static final RegistryObject<Item> RUBY = REGISTRY.register("ruby", () -> new RubyItem());
	public static final RegistryObject<Item> ENDERITE_SCRAP = REGISTRY.register("enderite_scrap", () -> new EnderiteScrapItem());
	public static final RegistryObject<Item> ENDERITE_INGOT = REGISTRY.register("enderite_ingot", () -> new EnderiteIngotItem());
	public static final RegistryObject<Item> RGB_GEM = REGISTRY.register("rgb_gem", () -> new RGBGemItem());
	public static final RegistryObject<Item> EMPTY_CORE = REGISTRY.register("empty_core", () -> new EmptyCoreItem());
	public static final RegistryObject<Item> ENDER_CORE = REGISTRY.register("ender_core", () -> new EnderCoreItem());
	public static final RegistryObject<Item> NETHER_CORE = REGISTRY.register("nether_core", () -> new NetherCoreItem());
	public static final RegistryObject<Item> WARDEN_CORE = REGISTRY.register("warden_core", () -> new WardenCoreItem());
	public static final RegistryObject<Item> WITHER_STORM_CORE = REGISTRY.register("wither_storm_core", () -> new WitherStormCoreItem());
	public static final RegistryObject<Item> COMMAND_CORE = REGISTRY.register("command_core", () -> new CommandCoreItem());
	public static final RegistryObject<Item> DIAMOND_STICK = REGISTRY.register("diamond_stick", () -> new DiamondStickItem());
	public static final RegistryObject<Item> RGB_STICK = REGISTRY.register("rgb_stick", () -> new RGBStickItem());
	public static final RegistryObject<Item> END_PORTAL_SLOT = REGISTRY.register("end_portal_slot", () -> new EndPortalSlotItem());
	public static final RegistryObject<Item> END_PORTAL_SIDE_FRAMES = REGISTRY.register("end_portal_side_frames", () -> new EndPortalSideFramesItem());
	public static final RegistryObject<Item> WITHERED_NETHER_STAR = REGISTRY.register("withered_nether_star", () -> new WitheredNetherStarItem());
	public static final RegistryObject<Item> RGB_STAR = REGISTRY.register("rgb_star", () -> new RGBStarItem());
	public static final RegistryObject<Item> END_ESSENCE = REGISTRY.register("end_essence", () -> new EndEssenceItem());
	public static final RegistryObject<Item> CREATIVE_ESSENCE = REGISTRY.register("creative_essence", () -> new CreativeEssenceItem());
	public static final RegistryObject<Item> WARDEN_HEART = REGISTRY.register("warden_heart", () -> new WardenHeartItem());
	public static final RegistryObject<Item> COAL_DUST = REGISTRY.register("coal_dust", () -> new CoalDustItem());
	public static final RegistryObject<Item> COPPER_DUST = REGISTRY.register("copper_dust", () -> new CopperDustItem());
	public static final RegistryObject<Item> IRON_DUST = REGISTRY.register("iron_dust", () -> new IronDustItem());
	public static final RegistryObject<Item> GOLD_DUST = REGISTRY.register("gold_dust", () -> new GoldDustItem());
	public static final RegistryObject<Item> RED_STONE_DUST = REGISTRY.register("red_stone_dust", () -> new RedStoneDustItem());
	public static final RegistryObject<Item> LAPIS_DUST = REGISTRY.register("lapis_dust", () -> new LapisDustItem());
	public static final RegistryObject<Item> DIAMOND_DUST = REGISTRY.register("diamond_dust", () -> new DiamondDustItem());
	public static final RegistryObject<Item> EMERALD_DUST = REGISTRY.register("emerald_dust", () -> new EmeraldDustItem());
	public static final RegistryObject<Item> NETHERITE_DUST = REGISTRY.register("netherite_dust", () -> new NetheriteDustItem());
	public static final RegistryObject<Item> MEATDUST = REGISTRY.register("meatdust", () -> new MeatdustItem());
	public static final RegistryObject<Item> MIXED_ORE_MEAT_INGOT = REGISTRY.register("mixed_ore_meat_ingot", () -> new MixedOreMeatIngotItem());
	public static final RegistryObject<Item> SENZU_BEAN = REGISTRY.register("senzu_bean", () -> new SenzuBeanItem());
	public static final RegistryObject<Item> COMMAND_BOOK = REGISTRY.register("command_book", () -> new CommandBookItem());
	public static final RegistryObject<Item> MELTED_NETHERITE = REGISTRY.register("melted_netherite", () -> new MeltedNetheriteItem());
	public static final RegistryObject<Item> MIXED_OREA_HELMET = REGISTRY.register("mixed_orea_helmet", () -> new MixedOreaItem.Helmet());
	public static final RegistryObject<Item> MIXED_OREA_CHESTPLATE = REGISTRY.register("mixed_orea_chestplate", () -> new MixedOreaItem.Chestplate());
	public static final RegistryObject<Item> MIXED_OREA_LEGGINGS = REGISTRY.register("mixed_orea_leggings", () -> new MixedOreaItem.Leggings());
	public static final RegistryObject<Item> MIXED_OREA_BOOTS = REGISTRY.register("mixed_orea_boots", () -> new MixedOreaItem.Boots());
	public static final RegistryObject<Item> AQUAMARINE_ARMOR_HELMET = REGISTRY.register("aquamarine_armor_helmet", () -> new AquamarineArmorItem.Helmet());
	public static final RegistryObject<Item> AQUAMARINE_ARMOR_CHESTPLATE = REGISTRY.register("aquamarine_armor_chestplate", () -> new AquamarineArmorItem.Chestplate());
	public static final RegistryObject<Item> AQUAMARINE_ARMOR_LEGGINGS = REGISTRY.register("aquamarine_armor_leggings", () -> new AquamarineArmorItem.Leggings());
	public static final RegistryObject<Item> AQUAMARINE_ARMOR_BOOTS = REGISTRY.register("aquamarine_armor_boots", () -> new AquamarineArmorItem.Boots());
	public static final RegistryObject<Item> RUBY_ARMOR_HELMET = REGISTRY.register("ruby_armor_helmet", () -> new RubyArmorItem.Helmet());
	public static final RegistryObject<Item> RUBY_ARMOR_CHESTPLATE = REGISTRY.register("ruby_armor_chestplate", () -> new RubyArmorItem.Chestplate());
	public static final RegistryObject<Item> RUBY_ARMOR_LEGGINGS = REGISTRY.register("ruby_armor_leggings", () -> new RubyArmorItem.Leggings());
	public static final RegistryObject<Item> RUBY_ARMOR_BOOTS = REGISTRY.register("ruby_armor_boots", () -> new RubyArmorItem.Boots());
	public static final RegistryObject<Item> OOF_ARMOR_HELMET = REGISTRY.register("oof_armor_helmet", () -> new OofArmorItem.Helmet());
	public static final RegistryObject<Item> OOF_ARMOR_CHESTPLATE = REGISTRY.register("oof_armor_chestplate", () -> new OofArmorItem.Chestplate());
	public static final RegistryObject<Item> OOF_ARMOR_LEGGINGS = REGISTRY.register("oof_armor_leggings", () -> new OofArmorItem.Leggings());
	public static final RegistryObject<Item> OOF_ARMOR_BOOTS = REGISTRY.register("oof_armor_boots", () -> new OofArmorItem.Boots());
	public static final RegistryObject<Item> ADMIN_ARMOR_HELMET = REGISTRY.register("admin_armor_helmet", () -> new AdminArmorItem.Helmet());
	public static final RegistryObject<Item> ADMIN_ARMOR_CHESTPLATE = REGISTRY.register("admin_armor_chestplate", () -> new AdminArmorItem.Chestplate());
	public static final RegistryObject<Item> ADMIN_ARMOR_LEGGINGS = REGISTRY.register("admin_armor_leggings", () -> new AdminArmorItem.Leggings());
	public static final RegistryObject<Item> ADMIN_ARMOR_BOOTS = REGISTRY.register("admin_armor_boots", () -> new AdminArmorItem.Boots());
	public static final RegistryObject<Item> MASTER_EMERALD_ITEM = REGISTRY.register("master_emerald_item", () -> new MasterEmeraldItemItem());
	public static final RegistryObject<Item> RING = REGISTRY.register("ring", () -> new RingItem());
	public static final RegistryObject<Item> ADMIN_RING = REGISTRY.register("admin_ring", () -> new AdminRingItem());
	public static final RegistryObject<Item> MIXED_ORE_BOW = REGISTRY.register("mixed_ore_bow", () -> new MixedOreBowItem());
	public static final RegistryObject<Item> MIXED_ORE_SWORD = REGISTRY.register("mixed_ore_sword", () -> new MixedOreSwordItem());
	public static final RegistryObject<Item> MIXED_ORE_AXE = REGISTRY.register("mixed_ore_axe", () -> new MixedOreAxeItem());
	public static final RegistryObject<Item> MIXED_ORE_SHOVEL = REGISTRY.register("mixed_ore_shovel", () -> new MixedOreShovelItem());
	public static final RegistryObject<Item> MIXED_ORE_PICK_AXE = REGISTRY.register("mixed_ore_pick_axe", () -> new MixedOrePickAxeItem());
	public static final RegistryObject<Item> MIXEDOREHOE = REGISTRY.register("mixedorehoe", () -> new MixedorehoeItem());
	public static final RegistryObject<Item> AQUAMARINE_SWORD = REGISTRY.register("aquamarine_sword", () -> new AquamarineSwordItem());
	public static final RegistryObject<Item> AQUAMARINE_AXE = REGISTRY.register("aquamarine_axe", () -> new AquamarineAxeItem());
	public static final RegistryObject<Item> AQUAMARINE_PICKAXE = REGISTRY.register("aquamarine_pickaxe", () -> new AquamarinePickaxeItem());
	public static final RegistryObject<Item> AQUAMARINE_SHOVEL = REGISTRY.register("aquamarine_shovel", () -> new AquamarineShovelItem());
	public static final RegistryObject<Item> AQUAMARINE_HOE = REGISTRY.register("aquamarine_hoe", () -> new AquamarineHoeItem());
	public static final RegistryObject<Item> RUBY_SWORD = REGISTRY.register("ruby_sword", () -> new RubySwordItem());
	public static final RegistryObject<Item> RUBY_AXE = REGISTRY.register("ruby_axe", () -> new RubyAxeItem());
	public static final RegistryObject<Item> RUBY_PICKAXE = REGISTRY.register("ruby_pickaxe", () -> new RubyPickaxeItem());
	public static final RegistryObject<Item> RUBY_SHOVEL = REGISTRY.register("ruby_shovel", () -> new RubyShovelItem());
	public static final RegistryObject<Item> RUBY_HOE = REGISTRY.register("ruby_hoe", () -> new RubyHoeItem());
	public static final RegistryObject<Item> OOF_SWORD = REGISTRY.register("oof_sword", () -> new OofSwordItem());
	public static final RegistryObject<Item> OOF_AXE = REGISTRY.register("oof_axe", () -> new OofAxeItem());
	public static final RegistryObject<Item> OOF_PICKAXE = REGISTRY.register("oof_pickaxe", () -> new OofPickaxeItem());
	public static final RegistryObject<Item> OOF_SHOVEL = REGISTRY.register("oof_shovel", () -> new OofShovelItem());
	public static final RegistryObject<Item> OOF_HOE = REGISTRY.register("oof_hoe", () -> new OofHoeItem());
	public static final RegistryObject<Item> ADMIN_STAFF = REGISTRY.register("admin_staff", () -> new AdminStaffItem());
	public static final RegistryObject<Item> OPM = REGISTRY.register("opm", () -> new OPMItem());
	public static final RegistryObject<Item> INCOMPLETE_ADMIN_STAFF = REGISTRY.register("incomplete_admin_staff", () -> new IncompleteAdminStaffItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
